### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by valle6** [monarkee/bumble#16]
I'm new in Laravel and I'm trying Bumble. I've gotten the errors above in the last commands of instalation:

root@debian3:/var/www/projects/dev/Laravel5b# php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "users" already exists  
   (SQL: create table "users" ("id" serial primary key not null, "name" varch  
  ar(255) not null, "email" varchar(255) not null, "password" varchar(60) not  
   null, "remember_token" varchar(100) null, "created_at" timestamp(0) withou  
  t time zone not null, "updated_at" timestamp(0) without time zone not null)  
  )                                                                            

  [PDOException]                                                               
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "users" already exists  

root@debian3:/var/www/projects/dev/Laravel5b# php artisan db:seed --class=BumbleSeeder

  [ReflectionException]              
  Class BumbleSeeder does not exist  

I'm using Debian 6 and PostgreSQL 9.

Solutions:
The first error was resolved deleting the file 2014-10-12_000000_create_users_table.php . This file come with Laravel.
The second error is not resolved. The instalation of Bumble does not create the BumbleSeeder.php and BumbleUsersTableSeeder.php classes in database / seeds . Even creating this files manually the problem persist.

I await guidance.

Regards.

**Comment by davidhemphill** [comment]
Hi there!

You can publish the seeder file and seed the database by running the following commands:

```
php artisan vendor:publish --provider="Monarkee\Bumble\Providers\BumbleServiceProvider" --tag="seeds"
composer update
php artisan db:seed --class=BumbleSeeder
```
