### ISSUE TITLE
run time error in laravel 5

### ISSUE THREAD

**Issue by abhitheawesomecoder** [monarkee/bumble#18]
I tried to install your cms in laravel 5 and at the end after generating auto-load file I got this :

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Illuminate\Foundation\Application::getCachedCompil
  ePath()

Script php artisan clear-compiled handling the post-update-cmd event returned wi
th an error

  [RuntimeException]
  Error Output:

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p
ackagesN]

**Comment by davidhemphill** [comment]
I'm not sure why you're getting this error. Did you happen to upgrade to Laravel 5.1? It doesn't have those commands in composer.json anymore.

**Comment by abhitheawesomecoder** [comment]
So it won't work with laravel 5.0 ?
