### ISSUE TITLE
dashboard 500 Internal Server Error

### ISSUE THREAD

**Issue by teodorsandu** [monarkee/bumble#21]
Hi, I have this error:

![image](https://cloud.githubusercontent.com/assets/5700488/9612916/9c0545a8-50e8-11e5-9ee3-c0107a8acf5a.png)

the response is:

![image](https://cloud.githubusercontent.com/assets/5700488/9612961/e666b654-50e8-11e5-9794-376d1d6cfa33.png)

I also noticed in console when runs ```php artisan serve```:
```[Tue Sep 01 20:28:29 2015] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in C:\wamp\www\laravel\bumble\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 2689```

Thank you

**Comment by davidhemphill** [comment]
Hi @teodorsandu, thanks for creating an issue. Do you have any more information we could use to reproduce this scenario?

**Comment by teodorsandu** [comment]
Hi @davidhemphill I've run again my current installation of bumbleCMS and get the same result. At that date(1 Sept) I followed the installation guide from http://bumblecms.com/docs/installation. 

I think your installation guide could be improved for newbies like me. I found not obvious to install laravel first (with e.g. ```laravel new mybumble```) and where to add ```"monarkee/bumble": "dev-master"```(to laravel's composer.json file). 
All went well until:
```
php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` int unsigne
  d not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `password` varchar(60) not nul
  l, `remember_token` varchar(100) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) defau
  lt character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists
```
That was because of  laravel's default migration file ```2014_10_12_000000_create_users_table.php``` from ```database/migrations/```, which I had to remove and solved the problem.

Finally I get it work and got this screen:
![image](https://cloud.githubusercontent.com/assets/5700488/10844233/4e1e7f46-7efe-11e5-8167-2fa90c69bb32.png)
I am missing something? this screenshot is very different from your website. My database is:
![image](https://cloud.githubusercontent.com/assets/5700488/10844309/d68224b4-7efe-11e5-935a-55be88e2ddb4.png)

**Comment by davidhemphill** [comment]
@teodorsandu Glad you got it working. If you use the migrations that come with Laravel (not everybody does), then you certainly get an error if you try to create the users table again. From this point, since it seems you only have a users table, you can register it by following these instructions: http://bumblecms.com/docs/models, http://bumblecms.com/docs/model-admins, and http://bumblecms.com/docs/fields.

As far as the Laravel requirement, I'm not sure what more we could say. The main title and subtitle of the homepage says "The CMS for *Laravel*: A beautiful auto-generated admin for your *Laravel* models."

**Comment by patrykgit** [comment]
Hi, I need to see your document to install bumble but it shows error
https://bumblecms.com/docs/installation
