### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::isHidden()

### ISSUE THREAD

**Issue by EuropeanRespiratorySociety** [monarkee/bumble#25]
BadMethodCallException in Builder.php line 2071: Call to undefined method Illuminate\Database\Query\Builder::isHidden()

I do not understand what generate this error (it is when I add one of my model)

**Comment by davidhemphill** [comment]
Can you post your model code? Without that, it's hard to tell, but it looks like your model isn't extending `Monarkee\Bumble\Models\BumbleModel`

**Comment by EuropeanRespiratorySociety** [comment]
My bad... sorry

**Comment by davidhemphill** [comment]
Glad you got it sorted!
