### ISSUE TITLE
 Trying to get property of non-object

### ISSUE THREAD

**Issue by ServerJunge** [monarkee/bumble#26]
Hi,

my user model 

    use Monarkee\Bumble\Models\BumbleModel;

    class User extends BumbleModel implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract

But i get the following error:

ErrorException in BumbleModel.php line 227:

Trying to get property of non-object

Can you help me?

**Comment by davidhemphill** [comment]
It appears that the $admin isn't being set. Make sure you've set up your admin like this: https://bumblecms.com/docs/model-admins
