### ISSUE TITLE
League\\Flysystem\\Filesystem::listPaths

### ISSUE THREAD

**Issue by LorenzV** [monarkee/bumble#3]
After composer install/update, laravel has an error. Can't do requests + artisan fails also. This is the error:

{"error":{"type":"BadMethodCallException","message":"Call to undefined method League\\Flysystem\\Filesystem::listPaths","file":"C:\\www\\bumble\\vendor\\league\\flysystem\\src\\Filesystem.php","line":713}}

**Comment by davidhemphill** [comment]
Hi guys! There's an issue where Flysystem removed the listPaths() method and added it to a plugin. I've got a fix coming tonight.

**Comment by flovan** [comment]
:+1:

**Comment by davidhemphill** [comment]
Ok, I pushed an update to the dependencies that should fix the issue @LorenzV is having. Let me know if that works!

@flovan I've been using Laravel 4.2 while developing, but you should have a fine experience with 4.1 as well. Laravel 5 is definitely too early :-)

**Comment by LorenzV** [comment]
Works! :)  Thanks
