### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gitllermopalafox** [monarkee/bumble#31]
Hi, great cms!

Which license has this project?

Greetings.

**Comment by arkid** [comment]
I'm also interested in clarification on this

**Comment by davidhemphill** [comment]
Hi there. I'm SUPER sorry for the silence. I've been away from Bumble for a long time! The birth of my second child and work craziness has kept me incredibly busy. I've updated the repo to add a license. I do plan on working on a free Laravel CMS product in the future, but Bumble is on hiatus until I can get back to it (or find one of the companies using it to sponsor some development time). I will however review and merge good pull requests if they happen to come in! 

Thank you so much for asking!

**Comment by gitllermopalafox** [comment]
Don't worry!, thanks for your answer.

Merry christmas!
