### ISSUE TITLE
Remove `user-select: none` from the doc CSS

### ISSUE THREAD

**Issue by flovan** [monarkee/bumble#4]
Due to this piece of CSS that is applied to the `body` in `marketing.css`, none of the website content can be selected or copied, which is actually pretty important when you have stuff like command line instructions and demo snippets;

````css
-webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
````

**Comment by davidhemphill** [comment]
This was fixed yesterday!
